
ARG STACK_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:8.1.1

#ADD ./config/elasticsearch.yml /usr/share/elasticsearch/config/
# USER root
# RUN chown elasticsearch:elasticsearch config/elasticsearch.yml
